### ISSUE TITLE
Error 500 install on Plesk 17.8 Update #19

### ISSUE THREAD

**Issue by five-team** [plesk/ext-diskspace-usage-viewer#36]
Way to reproduce: 
Download .zip
Upload Extension (it is already activated after upload) 
click on open
-> Error. 

Same issue after deactivation and activation.

**Comment by Kubik-Rubik** [comment]
Hello @five-team,

thank you for your report.

This extension is still in development and will be tested thoroughly by Plesk's QA team before the first release. You should wait until it is released officially in the Extension Catalog.

Cheers
